name: Build, Push & Deploy (using GitHub Secrets)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/github-secrets-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            IMAGE="${{ secrets.DOCKER_USERNAME }}/github-secrets-app:latest"

            # Ensure Docker is installed on EC2
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get -y install docker.io
              sudo systemctl enable --now docker
            fi

            # Authenticate & pull latest image
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || true
            sudo docker pull "$IMAGE"

            # Stop old container if running
            sudo docker stop gh-secrets-app || true
            sudo docker rm gh-secrets-app || true

            # Run new container
            sudo docker run -d --name gh-secrets-app -p 80:5000 --restart unless-stopped "$IMAGE"
