mkdir -p .github/workflows
cat > .github/workflows/deploy-with-secrets.yml <<'YML'
name: Build, Push & Deploy (using GitHub Secrets)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform safe builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/github-secrets-app:latest

      - name: Deploy to EC2 via SSH (uses EC2_SSH_KEY secret)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 30
          script: |
            set -e

            # ensure docker exists
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get -y install docker.io
              sudo systemctl enable --now docker
            fi

            # Login to Docker Hub on EC2 so private images can be pulled (if private)
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || true

            IMAGE="${{ secrets.DOCKER_USERNAME }}/github-secrets-app:latest"
            echo "Pulling image $IMAGE"
            sudo docker pull "$IMAGE"

            # stop/remove old container (if exists)
            sudo docker stop gh-secrets-app || true
            sudo docker rm gh-secrets-app || true

            # run new container on port 80 -> container port 5000
            sudo docker run -d --name gh-secrets-app -p 80:5000 --restart unless-stopped "$IMAGE"

            echo "Deployment succeeded."
YML

